apiVersion: v1
kind: Service
metadata:
  name: app-escalavel-svc
  labels:
    app: app-escalavel
spec:
  type: ClusterIP
  selector:
    app: app-escalavel
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    
